gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('gym_app.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gym_app/urls.py
from django.urls import path
from . import views

app_name = 'gym'

urlpatterns = [
    path('', views.Index.as_view(), name = 'index'),
    path('checkout/<int:pk>/', views.Checkout.as_view(), name = 'checkout'),
    path('plans/', views.PlansView.as_view(), name = 'plans'),
    path('success/', views.Success.as_view(), name = 'success'),
    path('cancel/', views.CancelView.as_view(), name = 'cancel'),
    path('help/', views.send_email, name = 'help_center'),
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('plan/<slug:slug>', views.PlanView.as_view(), name = 'plan'),
    path('account/', views.AccountView.as_view(), name = 'account'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name = 'register'),
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
]

gym_app/models.py
from distutils.command.upload import upload
from django.db import models

class MembershipPlan(models.Model):
    name = models.CharField(max_length = 100)
    description = models.TextField(null = True, blank = True)
    image = models.ImageField(null = True, blank = True, upload_to = 'images/')
    stripe_product = models.CharField(max_length = 150)

    def __str__(self):
        return self.name


class MembershipPlanPrice(models.Model):
    membership_plan = models.ForeignKey(MembershipPlan, related_name='plan', on_delete = models.CASCADE)
    price = models.IntegerField(null = False, blank = False)
    stripe_price = models.CharField(max_length = 150)

gym_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView, ListView, CreateView
from django.views import View
import stripe
from django.conf import settings
from django.core.mail import send_mail
from .models import MembershipPlan, MembershipPlanPrice
from users.models import Account, Membership
import datetime
from datetime import datetime as dt
from dateutil.relativedelta import relativedelta
from django.contrib import messages
stripe.api_key = settings.STRIPE_SECRET_KEY
class Index(TemplateView):
    template_name = 'gym_app/index.html'



class Checkout(View):
    def post(self, request, *args, **kwargs):
        price = MembershipPlanPrice.objects.get(id=self.kwargs["pk"])
        print(price.membership_plan)
        DOMAIN = 'http://127.0.0.1:8000'
        checkout_session = stripe.checkout.Session.create(
            payment_method_types  = ['card'],
            line_items = [
                {
                    'price' : price.stripe_price,
                    'quantity': 1,
                },
            ],
            mode = 'payment',
            success_url = DOMAIN + '/success/',
            cancel_url = DOMAIN,
        )
        # Check if user has active plan
        acc_user = Account.objects.get(user = self.request.user)
        query_date = Membership.objects.filter(account = acc_user).latest('date')
        iterable_query_date = Membership.objects.filter(account = acc_user)
        
        if query_date.date == datetime.date.today():
            return redirect('gym:index')
        if dt.today() < dt.today()+ relativedelta(months=1):
            return redirect('gym:index')
        else:
           for date in iterable_query_date:
                if date.date == datetime.date.today():
                    return redirect('gym:index')
                else:
                    user_progress =  Account.objects.get(user = self.request.user)
                    user_progress.user_progress += 1
                    Account.objects.filter(user = self.request.user).update(user_progress = user_progress.user_progress)
                    Membership.objects.create(account = acc_user, date = datetime.date.today(), membership_plan = price.membership_plan)

        return redirect(checkout_session.url)

class PlanView(TemplateView):
    template_name = "gym_app/plan.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        plan = MembershipPlan.objects.get(name = "Monthly Plan")
        price = MembershipPlanPrice.objects.filter(membership_plan = plan)

        context['plan'] = plan
        context['price_fields'] = price

        return context

class PlansView(ListView):
    template_name = 'gym_app/plans.html'
    model = MembershipPlan
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # gets all plans
        name_of_plans = MembershipPlan.objects.all()

        # Displays warning message to users that have active plan
        acc_user = Account.objects.get(user = self.request.user)
        query_date = Membership.objects.filter(account = acc_user).latest('date')

        if query_date.date == datetime.date.today():
            messages.warning(self.request, 'You bought gym plan today. If you buy another one it will not count in your progress track!')
        elif dt.today() < dt.today()+ relativedelta(months=1):
            messages.warning(self.request, "Your gym plan didn't expire yet. If you buy another one it will not count in your progress track!")
        else:
            pass
        context['name_of_plans'] = name_of_plans
        return context

class Success(TemplateView):
    template_name = 'gym_app/success.html'

        
class CancelView(TemplateView):
    template_name = 'gym_app/cancel.html'


def send_email(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        problem_description = request.POST['problem_description']
        send_mail(
            'User problem',
            'First name: '+first_name+'\nLast name: '+last_name +'\n'
            'Problem description: '+problem_description,
            email,
            ['stefan.programming22@gmail.com'],
        )
        return render(request, 'gym_app/help.html')

    
    return render(request, 'gym_app/help.html')


class AboutView(TemplateView):
    template_name = 'gym_app/about.html'


class AccountView(TemplateView):
    template_name = 'gym_app/account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        account_user = Account.objects.get(user = self.request.user)
        membership = Membership.objects.filter(account = account_user)
        stars = []
        for i in membership:
            print(i.account.user)
            print(i.date)
            print(i.plan)
            progress = i.date
            stars.append(progress)
        print(account_user)
        context['membership'] = membership
        context['account'] = account_user
        context['stars'] = stars
        
        return context

gym_app/templates/gym_app/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    Hi
</body>

</html>

gym_app/templates/gym_app/account.html
{%extends 'gym_app/base.html'%} {%load static%} {%block content%}

<section style="background-color: #eee;">
    <h1 class="text-center">Your profile</h1>
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img src="{{account.profile_pic.url}}" style='width:200px; height:200px;' alt="avatar"
                            class="rounded-circle img-fluid" style="width: 150px;">>


                        <h5 class="my-3">{{account.user.first_name}} {{account.user.last_name}}</h5>
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <div class="card-body p-0">
                        <ul class="list-group list-group-flush rounded-3">

                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                {% for i in stars%}
                                <i class="fa fa-star"></i>
                                {%endfor%}

                                <p class="mb-0">Gym progress</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Full Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{account.user.first_name}} {{account.user.last_name}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{account.user.email}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Instagram</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><a href="https://www.instagram.com/vukovicstefan2005/"
                                        style="color: orange; text-decoration: none;">vukovicstefan2005</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="card mb-4 mb-md-0">
                            <div class="card-body">
                                <p class="mb-4" style="color: #3b5998;">Gym membership
                                </p>
                                {%for pay in membership%}
                                <li class=" list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;">{{pay.date}}</i>
                                    <p class="mb-0">{{pay.plan}}</p>
                                </li>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="margin-bottom: 100px;"></div>
    </div>

</section>

{%endblock%}

gym_app/templates/gym_app/base.html
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <!--Nav bar-->
    <nav class="navbar navbar-light text-light" style="background-color: #19191a; font-size: 18px;">
        <ul class="nav justify-content-left mx-3">
            <li class="nav-item">
                <a href="{% url 'gym:index' %}" class="navbar-brand m-3 h1" style="color:orange">SUPREME</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'gym:plans' %}" class="nav-link" style="color:orange">Plans</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'gym:help_center' %}" class="nav-link text-light">Help center</a>
            </li>

        </ul>
        <!--Authentication is on the right side-->
        <ul class="nav justify-content-center mx-3">
            <li class="nav-item">
                <a href="{% url 'gym:about' %}" class="nav-link text-light">About us</a>
            </li>
            {%if request.user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'gym:account'%}" class="nav-link" style="color:orange">Account</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'users:logout'%}" class="nav-link text-light">Logout</a>
            </li>
            {%else%}
            <li class="nav-item">
                <a href="{% url 'users:login'%}" class="nav-link text-light">Login</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'users:register'%}" class="nav-link text-light">Register</a>
            </li>
            {%endif%}
        </ul>

    </nav>
    {% block content %}

    {% endblock %}
    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                        class="	fa fa-facebook-square"></i></a>

                <!-- Instagram -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                        class="	fa fa-instagram"></i></a>

                <!-- Linkedin -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                        class="fa fa-linkedin-square"></i></a>

                <!-- Twitter -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                        class="	fa fa-twitter-square"></i></a>

            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-white" href="/">Supreme</a>
        </div>
        <!-- Copyright -->
    </footer>
</body>

</html>

gym_app/templates/gym_app/cancel.html
{%extends 'gym_app/base.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {%block content%}

    {%endblock%}
</body>

</html>

gym_app/templates/gym_app/help.html
{% extends 'gym_app/base.html' %}


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {%block content%}

    <div style="margin-right: 20%; margin-left: 20%;">
        <section class="mb-4 ">
            <!--Section heading-->
            <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
            <!--Section description-->
            <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to
                contact us
                directly. Our team will come back to you within
                a matter of hours to help you.</p>
            <div class="row d-flex justify-content-center">
                <!--Grid column-->
                <div class="col-md-9 mb-md-0 mb-3">
                    <form id="contact-form" name="contact-form" action="{% url 'gym:help_center' %}" method="POST"
                        class="form-horizontal">
                        {%csrf_token%}
                        <!--Grid row-->
                        <div class="row">
                            <!--Grid column-->
                            <div class="col-md-6 form-group">
                                <div class=" md-form mb-3">
                                    <label for="first_name" class="">First name</label>
                                    <input type="text" id="first_name" name="first_name" class="form-control"
                                        placeholder="First name">
                                </div>
                            </div>

                            <!--Grid column-->
                            <div class="col-md-6 form-group">
                                <div class="md-form mb-0">
                                    <label for="last_name" class="">Last name</label>
                                    <input type="text" id="last_name" name="last_name" class="form-control"
                                        placeholder="Last name">
                                </div>
                            </div>

                            <!--Grid column-->
                            <div class="col-md-6 form-group">
                                <div class="md-form mb-4">
                                    <label for="email" class="">Your email</label>
                                    <input type="text" id="email" name="email" class="form-control" placeholder="Email">
                                </div>
                            </div>
                            <!--Grid column-->

                        </div>
                        <!--Grid row-->

                        <!--Grid row-->
                        <div class="row">
                            <!--Grid column-->
                            <div class="col-md-12">
                                <div class="md-form mb-4">
                                    <label for="problem_description">Problem</label>
                                    <textarea type="text" id="problem_description" name="problem_description" rows="2"
                                        class="form-control md-textarea" placeholder="Describe your problem"></textarea>
                                </div>
                            </div>
                        </div>
                        <!--Grid row-->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary" style="width: 100px;">Send</button>
                        </div>
                    </form>
                </div>
                <!--Grid column-->

            </div>

            <div style="margin-bottom: 300px;"></div>
        </section>
    </div>
    </div>

    {%endblock%}
</body>

</html>

gym_app/templates/gym_app/index.html
{%extends 'gym_app/base.html'%} {%load static%}


{%block content%}
<link rel="script" href="{% static 'javascript/index.js' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css" />
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>




<div class="container">
    <div class="text-center">
        <h1><span style="color: #fd7e14;;">Supr</span>eme G<span style="color: #fd7e14;;">ym</span></h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, debitis!</p>
    </div>
    <!--Image slideshow-->
    <div class="container-slide">
        <div class="swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                <div class="swiper-slide"><img src="{% static 'images/gym_1.jpg' %}" alt=""></div>
                <div class="swiper-slide"><img src="{% static 'images/gym_1.jpg' %}" alt=""></div>
                <div class="swiper-slide"><img src="{% static 'images/gym_1.jpg' %}" alt=""></div>

            </div>
            <!-- If we need pagination -->
            <div class="swiper-pagination"></div>

            <!-- If we need navigation buttons -->
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>

        </div>
        <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
        <script src="{% static 'javascript/index.js' %}"></script>
    </div>

    <!--Ends-->



    <!--About section-->
    <div class="about mt-5">
        <p class="h1 text-center mb-4">About us</p>
        <section class="row mb-5">

            <img src="{% static 'images/gym_1.jpg' %}" alt="" class="col-7" style="height: 350px;">


            <div class="col-5">
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Porro nihil at sed neque, assumenda
                    provident sit maiores ab accusantium dolorem, velit repellendus quis itaque! Quae aliquam fugit
                    sunt, hic corporis ea, eaque rerum autem possimus corrupti delectus provident doloribus amet
                    eligendi accusantium aliquid ducimus voluptatibus tenetur accusamus, officia voluptatem. Minima!
                    <a href="#">Learn more</a>
                </p>
            </div>
        </section>
    </div>
    <!--Google maps-->
    <div class="container">
        <p class="h1 text-center">Find us</p>
        <section class="row mb-5 mt-4">

            <div class="col text-center">

                <ul class="list-group list-group-light list-group-small text-start">
                    <li class="list-group-item"><span style="font-weight: 500; color: #6610f2;">Address:</span>
                        Bulevar vojvode
                        Stepe Stepanovića 132</li>
                    <li class="list-group-item"><span style="font-weight: 500; color: #6610f2;">Email:</span>
                        petevog776@imdutex.com
                    </li>
                    <li class="list-group-item"><span style="font-weight: 500; color: #6610f2;">Phone 1:</span>
                        806-294-8622</li>
                    <li class="list-group-item"><span style="font-weight: 500; color: #6610f2;">Phone 2:</span>
                        214-633-5866</li>
                </ul>
                <br>
                <p class="h4 mt-3">Working hours</p>
                <ul class="list-group text-start">
                    <li class="list-group-item" style="border:none; border-bottom: 1px solid black; width: 350px;">
                        Monday - Saturday: from 06:30 to 23:00</li>
                    <li class="list-group-item" style="border:none; border-bottom: 1px solid black; width: 350px;">
                        Sunday: from 12:00 to 21:00</li>

                </ul>
                <div class="d-grid gap-2 d-md-flex justify-content-md-start mt-4">
                    <button class="btn me-md-2 w-50 hover-zoom"
                        style="width: 200px; height:50px; background-color: #19191a;"><a
                            href="{% url 'gym:help_center' %}" style="color: white; text-decoration: none;">Contact
                            us</a></button>
                </div>
            </div>
            <!--The div element for the map -->
            <div id="map" class="col"></div>
            <script src="{% static 'javascript/index.js' %}"></script>
            <!--API-->
            <script
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBa-QjKsrPaQM579G8vQdK3ER03sYGG5TY&callback=initMap&v=weekly"
                defer></script>

        </section>
    </div>
    <!--Ends-->
</div>
{%endblock%}

gym_app/templates/gym_app/plan.html
{% extends 'gym_app/base.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {%block content%}
    <!--Monthly plans-->
    <section>
        {{plan.name}}
        {%for price in price_fields%}
        <form action="{% url 'gym:checkout' price.id %}" method="post">
            {%csrf_token%}
            <button type="submit">Checkout</button>
        </form>
        {%endfor%}
    </section>
    {%endblock%}
</body>

</html>

gym_app/templates/gym_app/plans.html
{%extends 'gym_app/base.html'%} {%load static%} {%block content%}
<link rel="stylesheet" type="text/css" href="{% static 'css/plans.css' %}" />
{% if messages %}
{% for message in messages %}
<div class="container-fluid p-0">
    <div class="alert {{ message.tags }}" role="alert" style="text-align: center;">
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}
<div class="text-center">
    <h1 style="font-size: 44px; color: 
    #ed3b3b
    ;">Our gym plans</h1>
    <p style="font-size: 16px; color: 
    #3bafed
    ;">Chose plan according to your goals!</p>
</div>
<div class="container">
    <div class="row">
        {% for plan in name_of_plans%}
        <div class="col me-3 hover-div">
            <h2 style="border-bottom:1px solid orange; " class=" text-center p-2">{{plan.name}}</h2>
            <img src="{{plan.image.url}}" alt="" style="width: 100%; height: 200px">
            <p class="lh-base">{{plan.description}}</p>


            {%for pricee in plan.plan.all%}
            <p style="border-bottom:1px solid orange;" class="fs-3">Price: {{pricee.price}}USD</p>


            <form action="{% url 'gym:checkout' pricee.id %}" method="post">
                {%csrf_token%}
                <div class="d-grid gap-2 col-6 mx-auto">
                    <button class="btn btn-success" type="submit">Buy now</button>
                </div>
            </form>

            {%endfor%}

            <br><br>
        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

gym_app/templates/gym_app/success.html
{%extends 'gym_app/base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {%block content%}
    <h1>You purchase was succesful!</h1>
    <p>Thank you for your purchase <a href="{% url 'gym:index' %}">Go to home page</a></p>

    {%endblock%}
</body>

</html>